/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/budgie.glb 
Author: _alexseptember_ (https://sketchfab.com/Blkwidowp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/budgie-96b64cf450104453b4de3a43b401637f
Title: Budgie
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function Budgie(props) {
  const { nodes, materials } = useGLTF('/models/budgie.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Nails} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Body_Mat} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Eyes_Mat} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Feet_Mat} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Nose1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Tongue_Mat} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Wings_Mat} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Beak_Mat} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/budgie.glb')


export default Budgie;